name: ecommerce_2023
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  persistent_bottom_nav_bar_v2: ^4.2.5
  firebase_core: ^2.2.0
  firebase_auth: ^4.0.2
  cloud_firestore: ^4.0.2
  provider: ^6.0.4
  awesome_snackbar_content: ^0.1.0
  intl: ^0.17.0
  bloc: ^8.1.0
  # conditional_builder: ^1.0.2
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  # see https://flutter.dev/custom-fonts/#from-packages
